# run 'pre-commit install' to update changes
# run 'pre-commit run --all-files' to run manually
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      # format stuff
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # check stuff
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config ./pyproject.toml]
      - id: black-jupyter
        args: [--config ./pyproject.toml]

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.1
    hooks:
      - id: pylint
