name: Black & Pylint
on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      # check-out repo and set-up python
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # load pip cache if cache exists
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      # install black
      - run: python -m pip install black
      - run: black . --check --config ./pyproject.toml

  pylint:
    runs-on: ubuntu-latest
    steps:
      # check-out repo and set-up python
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      # load pip cache if cache exists
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: ${{ runner.os }}-pip
      # install pylint
      - run: python -m pip install pylint
      - run: pylint --recursive=y --rcfile=./pyproject.toml .
